language: node_js
node_js:
  - lts/*
script:
  - npm install
  - npm run generate
deploy:
  provider: pages
  local-dir: dist
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  on:
    branch: master
    repo: viasite/planfix-toggl-client
